### ISSUE TITLE
Generates blank PNGs

### ISSUE THREAD

**Issue by petewarman** [filamentgroup/grumpicon#28]
I have a bunch of national flags in svg format I'm trying to convert but the generated PNGs (and the data-uri encoded versions) all seem to be blank. Any ideas?

Here's the US flag as an example https://dl.dropboxusercontent.com/u/62488531/USA.svg

**Comment by dougatempirical** [comment]
This issue might have reared its head again.

Using Firefox 48, SVGs that I've uploaded all generate a 30x30 blank PNG.

Here's the text of one of the SVGs that does it for me:
`<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 50 50"><path d="M42.6 15.1l-18 19.2L6.5 15.1.9 21l23.7 25.2L48.2 21z" class="content"/></svg>`
