### ISSUE TITLE
PNG fallbacks not in folder

### ISSUE THREAD

**Issue by shshaw** [filamentgroup/grumpicon#35]
The `.png` files for the fallback are not placed in the folder specified with the `pngfolder` option, but they are referenced based on that folder in the `icons.fallback.css` file.

Love using grumpicon, but I have to manually drop the PNGs in the folder every time.

**Comment by ericponto** [comment]
The `pngfolder` option isn't working correctly. I addressed this in PR #46.

**Comment by ericponto** [comment]
The fix is merged and I just tested it out and it looks like it is working.
