### ISSUE TITLE
Doesn't let me input SVG

### ISSUE THREAD

**Issue by IronCraftMan** [filamentgroup/grumpicon#40]
http://www.grumpicon.com doesn't let me drag a SVG in. No errors, nothing. I have tried with different ones, but still fails. there should be a "Choose File" button.

**Comment by DecipherOne** [comment]
After trying to use this service today, with much success in the past, I am not able to drag and drop from chrome. It is only working in firefox.

**Comment by DecipherOne** [comment]
Day two of trying different methods to remedy this and still no success so far. I am abandoning this web app until the issue has been resolved, and instead will look at using grunticon in my build process.

**Comment by jefflembeck** [comment]
@DecipherOne any chance you can shoot us a link to that svg so we can test?

**Comment by DecipherOne** [comment]
@jefflembeck Sure, here is a link to the svg. https://dl.dropboxusercontent.com/u/1568091/CRTDev/optimised.svg
System is windows 7 service pack 1, attempted to drop with chrome version Version 45.0.2454.101 m
and ie 11 version 11.0.9600.17959 with no success.

When I was able to get it to drop in firefox, but not display properly in other browsers, here was the generated files. https://dl.dropboxusercontent.com/u/1568091/CRTDev/FFOnlyGeneratedsvg.zip

**Comment by mdmcginn** [comment]
I tried Chrome, Edge and Firefox, and never got a Downlode button,, either after selecting this file for upload or after dragging it:  https://www.dropbox.com/s/chsx2tbulde4f43/crop.colors-green.svg?dl=0
