### ISSUE TITLE
Fix website

### ISSUE THREAD

**Issue by ldexterldesign** [filamentgroup/grumpicon#43]
Hey,

http://www.grumpicon.com/ appears broken - I drop my SVGs and nothing happens

Anyone else have this issue?

Yours hopefully,

**Comment by jefflembeck** [comment]
Hey @ldexterldesign,

Which browser (version # and operating system)? Is there an error in the console? Does it happen with just one of your SVGs? - That'll help us recreate your issue so we can fix it quickly. Thanks!

**Comment by ldexterldesign** [comment]
Google Chrome v39.0.2171.99 (64-bit) OS X Yosemite

Seems to working fine now, so ignore me

Apologies,
