### ISSUE TITLE
set 'background-repeat: no-repeat;' with an attribute selecter

### ISSUE THREAD

**Issue by Jugibur** [filamentgroup/grumpicon#45]
If using a lot of icons, it could be more efficient, to remove 'background-repeat: no-repeat' from each icon and declare a attribute selector to set this code, like so:

[class^="icon-"] {
  background-repeat: no-repeat
}

**Comment by ericponto** [comment]
We try to keep this as close to the grunticon output as possible. I'd suggest adding the issue on that repo (https://github.com/filamentgroup/grunticon/issues) if you'd like to see it added.

**Comment by jefflembeck** [comment]
@ericponto this is something we solve on Grunticon by allowing users to reference a template file for their css - not sure how to apply that here yet

**Comment by ericponto** [comment]
@jefflembeck - Alright, that makes sense. We could add that to the config and have a `<textarea>` for  the handlebars template. To hit all of these different options the config could get pretty big...but it is more of an advanced feature.

**Comment by ericponto** [comment]
I addressed this in PR #46 and added a config for a custom template for the CSS output.
