### ISSUE TITLE
Colors seem not to be working

### ISSUE THREAD

**Issue by jtbr** [filamentgroup/grumpicon#51]
I add the following colors string in grumpiconfig, following the options documentation example: 
`{ wh: "#ffffff", bk: "#000000", lt: "#bbbbbb", dk: "#444444", fb: "#3b5998", tw: "#55acee", gp: "#dd4b39", pi: "#bd081c" }`

Then I drop a file named `angle-left.colors-wh-lt-dk.svg` (which itself has no fill color/is black, which is the final color I want besides wh/lt/dk). (The other colors would be for other files that I would add)

I only get a single png/svg back, in black. Am I doing something wrong? I've tried single/double/no quotes for the color string and enclosing braces or not. After closing and re-opening grumpiconfig it always is enclosed in double quotes, possibly along with escaping; perhaps this is the cause of the problem? I also tried with and without a fill (color) command in the svg file.  I always get only one black png back (when I was expecting either a sprite with all the colors (this is what I was hoping for) or multiple pngs (one for each color)) [Note that I'm only focusing on the png because it's easier to verify than the svg data URIs].

Great webapp, hope I can get this working.

![grumpi](https://cloud.githubusercontent.com/assets/13181111/9473281/448a87c2-4b5a-11e5-8f08-38db8eee02f5.png)

**Comment by ericponto** [comment]
The code is using `JSON.parse` on the color option...so the props need to be in double quotes. That should probably be documented better.

**Comment by jtbr** [comment]
Those double quotes do seem to be added automatically, but the colors still don't work (same if I add them manually). E.g.: "{wh: \"#ffffff\",bl: \"#000000\",lt: \"#bbbbbb\",dk: \"#444444\",fb: \"#3b5998\", tw: \"#55acee\", gp: \"#dd4b39\", pi: \"#bd081c\", em: \"#ffbb4d\"}"

Only one file is generated, rather than what should be four in the example.

**Comment by ericponto** [comment]
You need double quotes around the property names like this:

```
 {"wh": "#ffffff","bl": "#000000","lt": "#bbbbbb","dk": "#444444","fb": "#3b5998", "tw": "#55acee", "gp": "#dd4b39", "pi": "#bd081c", "em": "#ffbb4d"}
```

**Comment by jtbr** [comment]
That works. Thanks.
