### ISSUE TITLE
Grumpiconfig: named colors:{} are not respected?

### ISSUE THREAD

**Issue by bendrexl** [filamentgroup/grumpicon#53]
Adding this to the colors field:
```javascript
{'steel': '#b3b3b3', 'charcoal':'#454545'}
```
...with the filename: 
`myicon.colors-white-steel-charcoal.svg`

...nets me two output icons: 
`myIcon` with the original SVG colors
`myIcon-white` which is white as expected.

The other two named color options are ignored. I've tried a few different variants, but only standard color names and hex codes seem to work. Maybe my syntax is wrong, but I've tried a bunch of variants without any luck.

I'm actually trying Grum**p**icon because I can't get Grun**t**icon to paint my icons at all, no matter what I name them or how I format the colors object, so maybe this is a bigger problem?

**Comment by ericponto** [comment]
Try using double quotes instead of single in the color field.

**Comment by bendrexl** [comment]
Yep, you're right... resetting local storage and pasting in:
`{"ash": "#fff", "steel": "#b3b3b3", "charcoal":"#454545"}`

Works just fine. Now if I can get Grunticon working as well, I'll be set.

Thanks

**Comment by bendrexl** [comment]
I'll close this, here's a link to the Grun**t**icon issue: https://github.com/filamentgroup/grunticon/issues/298
