### ISSUE TITLE
Create Alternative to Drag and Drop Interface

### ISSUE THREAD

**Issue by malchata** [filamentgroup/grumpicon#55]
Grumpicon is great, and I like using it, but the drag and drop interface is kind of unwieldy in my opinion. Is it possible to have an alternative file uploader where we can click a button and choose which files to upload from a system file browser?

**Comment by ericponto** [comment]
I'm in favor of this idea. I can probably try to get that implemented soon.

**Comment by malchata** [comment]
Thanks @ericponto! You rock.

**Comment by malchata** [comment]
Amazing turnaround on this. Thanks again!
