### ISSUE TITLE
404

### ISSUE THREAD

**Issue by Primajin** [filamentgroup/grumpicon#58]
I wanted to try out grumpicon website, but when i drag and drop my folder with 18 svg in I only get 

```
blob:http://www.grumpicon.com/7ebfdf27-0a5f-4852-9395-aaa5eb394cb7 Failed to load resource: the server responded with a status of 404 (Not Found)
```

in the console.
MacOSX Sierra, Chrome Canary, Safari 10, Chrome (no error, but nothing happens)

When I use 'click 2 open' and then go cmd+a, I'm getting a dozen 

```
Uncaught TypeError: Cannot read property 'replace' of undefined
    at http://www.grumpicon.com/public/dist/grumpicon.min.js:9:10598
```

and also the folder itself is listed as an icon, although not selected

**Comment by johnbender** [comment]
@Primajin 

In `package.json` make the following change:

```
...
   "grunt-grunticon": "~2.1.1",
...
```

to

```
...
   "grunt-grunticon": "~2.3.0",
...
```

Then run `npm install` again before starting the web app.

**Comment by johnbender** [comment]
@Primajin 

@jefflembeck pointed out that you are likely just using the website. The above advice only applies if you are hosting the website on your laptop. 

Otherwise maybe you can post your assets somewhere for use so we can try to debug?

**Comment by Primajin** [comment]
Yes the website. Sorry for the confusion. Here are the files.
[icons.zip](https://github.com/filamentgroup/grumpicon/files/496142/icons.zip)

**Comment by Primajin** [comment]
Seemed to be a problem with the files itself. I recreated all of the svgs and now I don't have a problem anymore.
