### ISSUE TITLE
Black images if <style> in svg

### ISSUE THREAD

**Issue by MatsSvensson** [filamentgroup/grumpicon#60]
I had some problems with some SVGs  causing all black images.
I found the following:

**Works:**
```
<svg xmlns="http://www.w3.org/2000/svg" preserveAspectRatio="xMinYMin" viewBox="0 0 245 358">
<path style="fill:green" d="M50.1 201.8c0-2.9 2.4-5.3 5.3-5.3 2.9 0 5.3 2 5.3 4.6 0 2.7-2.6 4.8-5.9 4.8C52.2 206 50.1 204 50.1 201.8z" />
</svg>
```

**Doesnt work:**
```
<svg xmlns="http://www.w3.org/2000/svg" preserveAspectRatio="xMinYMin" viewBox="0 0 245 358">
<style>.a{fill:green}</style>
<path class="a" d="M50.1 201.8c0-2.9 2.4-5.3 5.3-5.3 2.9 0 5.3 2 5.3 4.6 0 2.7-2.6 4.8-5.9 4.8C52.2 206 50.1 204 50.1 201.8z" />
</svg>
```

I did lots of experimenting, and could find no way to get images if i used <style> in the svg.

Otherwise **great** stuff, very useful.

**Comment by ericponto** [comment]
Is this happening on a certain browser? I tried using your "Doesn't work" example in Chrome and it worked as expected.

**Comment by MatsSvensson** [comment]
Weird.
It seems to work now.

Same files, no changes.
I tried with lots of files, and changes, and it was always the <style> that was the deal-breaker.
...and now they all work.

Maybe some fix to something was rolled out.
Or the planets was just in the wrong position back then.

Oh well...
